# Generated by Django 4.1.3 on 2022-12-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0002_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
