# Generated by Django 4.1.3 on 2022-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0003_prodmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='newmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('kerala', 'kerala'), ('karnataka', 'karnataka'), ('tamilnadu', 'tamilnadu')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='prodmodel',
        ),
    ]
