# Generated by Django 4.1.3 on 2022-12-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0004_newmodel_delete_prodmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('customername', models.CharField(max_length=20)),
                ('customerid', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
